replicaCount: 2

image:
  repository: docker.io/karimzakzouk/graduation-project-devops
  pullPolicy: IfNotPresent
  tag: 83849bd04868cccd57a5a4c85af60fd9995a99c7

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

namespace: ""

securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  allowPrivilegeEscalation: false


resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
