replicaCount: 1

image:
  repository: docker.io/karimzakzouk/graduation-project-devops
  pullPolicy: IfNotPresent
  tag: 9a23dbb2203f7d6390fa321a931b74b1d1a3fcbd

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

namespace: ""

securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  allowPrivilegeEscalation: false


resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

karpenter:
  nodepool:
    name: solar-nodepool
    capacityTypes: ["spot", "on-demand"]
    architecture: ["amd64"]
  nodeclass:
    name: solar-nodeclass
    role: "KarpenterNodeRole-solar-system-app-cluster"
    amiFamily: AmazonLinux2023
    clusterName: "solar-system-app-cluster"
    instanceProfile: KarpenterNodeInstanceProfile
